from __future__ import annotations

from homeassistant.const import CONF_PASSWORD, CONF_USERNAME, Platform

DOMAIN = "audiconnect"

CONF_VIN = "vin"
CONF_DEVICE_ID = "device_id"
CONF_CARNAME = "carname"
CONF_ACTION = "action"
CONF_CLIMATE_TEMP_F = "temp_f"
CONF_CLIMATE_TEMP_C = "temp_c"
CONF_CLIMATE_GLASS = "glass_heating"
CONF_CLIMATE_SEAT_FL = "seat_fl"
CONF_CLIMATE_SEAT_FR = "seat_fr"
CONF_CLIMATE_SEAT_RL = "seat_rl"
CONF_CLIMATE_SEAT_RR = "seat_rr"
CONF_CLIMATE_AT_UNLOCK = "climatisation_at_unlock"
CONF_CLIMATE_MODE = "climatisation_mode"
CONF_SCAN_INITIAL = "scan_initial"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_API_LEVEL = "api_level"
CONF_DURATION = "duration"
CONF_TARGET_SOC = "target_soc"

MIN_UPDATE_INTERVAL = 15
DEFAULT_UPDATE_INTERVAL = 15
UPDATE_SLEEP = 5
DEFAULT_API_LEVEL = 0

CONF_SPIN = "spin"
CONF_REGION = "region"
CONF_FILTER_VINS = "filter_vins"

REFRESH_VEHICLE_DATA_FAILED_EVENT = "refresh_failed"
REFRESH_VEHICLE_DATA_COMPLETED_EVENT = "refresh_completed"

REGION_EUROPE = "DE"
REGION_CANADA = "CA"
REGION_USA = "US"
REGION_CHINA = "CN"

REGIONS: dict[int, str] = {
    1: REGION_EUROPE,
    2: REGION_CANADA,
    3: REGION_USA,
    4: REGION_CHINA,
}

API_LEVELS: list[int] = [0, 1]

PLATFORMS: list[Platform] = [
    Platform.BINARY_SENSOR,
    Platform.SENSOR,
    Platform.DEVICE_TRACKER,
    Platform.LOCK,
    Platform.SWITCH,
]

__all__ = [
    "API_LEVELS",
    "CONF_ACTION",
    "CONF_API_LEVEL",
    "CONF_CARNAME",
    "CONF_DEVICE_ID",
    "CONF_CLIMATE_AT_UNLOCK",
    "CONF_CLIMATE_GLASS",
    "CONF_CLIMATE_MODE",
    "CONF_CLIMATE_SEAT_FL",
    "CONF_CLIMATE_SEAT_FR",
    "CONF_CLIMATE_SEAT_RL",
    "CONF_CLIMATE_SEAT_RR",
    "CONF_CLIMATE_TEMP_C",
    "CONF_CLIMATE_TEMP_F",
    "CONF_DURATION",
    "CONF_FILTER_VINS",
    "CONF_PASSWORD",
    "CONF_REGION",
    "CONF_SCAN_INTERVAL",
    "CONF_SCAN_INITIAL",
    "CONF_SPIN",
    "CONF_TARGET_SOC",
    "CONF_USERNAME",
    "CONF_VIN",
    "DEFAULT_API_LEVEL",
    "DEFAULT_UPDATE_INTERVAL",
    "DOMAIN",
    "MIN_UPDATE_INTERVAL",
    "PLATFORMS",
    "REFRESH_VEHICLE_DATA_COMPLETED_EVENT",
    "REFRESH_VEHICLE_DATA_FAILED_EVENT",
    "REGIONS",
    "UPDATE_SLEEP",
]
